### ISSUE TITLE
There is no images. All the images are replaced with dark squares 

### ISSUE THREAD

**Issue by FatehMammadli** [blyad2137/google-dark-theme#1]
![Snipaste_2021-08-10_17-50-20](https://user-images.githubusercontent.com/76201120/128878952-a67abb2d-9122-42fe-9011-c5c05a6bc015.png)

**Comment by blyad2137** [comment]
Sorry for not responding, I was AWOL for a week. Responding to your issue you clearly using something else with my theme. There is no way background is overalapping the images due to everything being done in 'background-color', not 'background'. Other style must override mine.

![image](https://user-images.githubusercontent.com/86572965/129456334-7e6a4d0e-15d2-4d60-a39f-2beef54698ef.png)

**Comment by blyad2137** [comment]
I would highly recommend to check source code(ctrl+shift+c).

**Comment by FatehMammadli** [comment]
No problem thank you for responding I am very grateful for that. And man this is really nice css. Not going to lie the best one I have ever seen. Works with google photo google drive. Just amazing. Good job. Keep it up. I will try to find solution for my problem.

**Comment by FatehMammadli** [comment]
I found out the problem. It doesn't work with Google Force dark mode. If it could that would be amazing

**Comment by blyad2137** [comment]
Unfortunately it is not possible to make it work with forced dark mode from Opera GX, you can adjust domains at settings in which it works or not. 

And thanks for those kind words, if you are doing something make it best possible.

**Comment by FatehMammadli** [comment]
[image: image.png][image: image.png]
I was able to find one thing. If I am going to turn off the block
thing on .wXeWr
it will show the images. But the placement off the images gets little bit
messy

**Comment by blyad2137** [comment]
Well thats the charm of running two separate stylesheets.
At least it works, kinda

**Comment by FatehMammadli** [comment]
Could you help me with that or you are busy and don't want to. If you are I
totally get it

**Comment by FatehMammadli** [comment]
Found better solution
