### ISSUE TITLE
Add "images" to RegExp

### ISSUE THREAD

**Issue by MoneyAllDay** [blyad2137/google-dark-theme#12]
If you could add "images" to the RegExp so when viewing the link "https://images.google.com/" the style is activated as well.

**Comment by blyad2137** [comment]
Sorry for late response, but I was too lazy playing FH5.
And yea sure, didn't even realize that there is such domain.

**Comment by blyad2137** [comment]
Tho new update might take a while, I need to write the entire firebase.
