### ISSUE TITLE
Google Calendar - Month view, 2 week view and calendar weeks are missing

### ISSUE THREAD

**Issue by xlsigned** [blyad2137/google-dark-theme#13]
Version: 3.1.0
- Background is still light
- Text is still dark
- Label colors are still for light background

**Comment by blyad2137** [comment]
This should do the trick, just paste this somewhere for now
`	.hero-content .hero-heading {
		color: var(--white-3);
	}
	.hero-content .hero-description, .hero-signup-cta, .page-content .section-page-break a, .glue-header__link:visited, .glue-header__logo-link:visited {
		color: var(--grey-1);
	}
	.glue-button--high-emphasis.glue-social__copy-btn:hover, .glue-button--high-emphasis.glue-social__title.glue-social__title--zippy.glue-expansion-panel-toggle:hover, .glue-button.glue-button--high-emphasis:hover {
		background-color: var(--devsite-button-primary-background-hover);
	}
	.glue-button--high-emphasis.glue-social__copy-btn, .glue-button--high-emphasis.glue-social__title.glue-social__title--zippy.glue-expansion-panel-toggle, .glue-button.glue-button--high-emphasis {
		background-color: var(--blue);
		color: var(--bg-dark);
	}
	.glue-header__bar--desktop .sign-in--link:visited {
		color: var(--blue);
	}
	.glue-button--medium-emphasis.glue-social__copy-btn:visited, .glue-button--medium-emphasis.glue-social__title.glue-social__title--zippy.glue-expansion-panel-toggle:visited, .glue-button.glue-button--medium-emphasis:visited {
		background-color: var(--bg-dark);
		color: var(--blue);
	}
	.docs-homescreen-gb-container div input {
		color: var(--white-1) !important;
	}
	.gssb_e {
		background-color: var(--bg-dark);
		border-color: var(--border-52);
	}
	.gssb_m {
		color: var(--whie-1);
		background-color: var(--bg-dark);
	}
	.PhLhOd, .tNDBE:not(.Wyo4Qe), .QIadxc, .t8qpF, .d3Ig7c, .L1Ysrb {
		border-color: var(--border-1);
	}
	.tNDBE {
		background-color: var(--bg-dark);
	}
	.zYZlv {
		border-color: var(--border-1);
		color: var(--grey-2);
	}
	.dkNwF .yzYBvd, .SOVd1b, .dtaVuc {
		color: var(--white-4);
	}
	.yzYBvd:hover, .SOVd1b:hover {
		background-color: var(--bg-dark-2);
	}
	.wy3aMe, .yzYBvd, .OmwDud {
		color: var(--grey-2);
	}
	.OmwDud.F262Ye {
		color: var(--blue);
	}
	.OmwDud.F262Ye .SOVd1b {
		background-color: var(--blue);
		color: var(--bg-dark);
	}
	.OmwDud.F262Ye .SOVd1b:hover {
		background-color: var(--devsite-button-primary-background-hover);
	}
	.wcJUvc::-webkit-scrollbar-thumb {
		border-color: var(--bg-dark);
	}
	div.rF3YF .NMm5M, div.rF3YF .Ce1Y1c {
		color: var(--grey-1);
		fill: var(--grey-1);
	}`

**Comment by xlsigned** [comment]
Looks good now. Thanks a lot!
