### ISSUE TITLE
Chart Alteration on Google Sheets

### ISSUE THREAD

**Issue by C4J3** [blyad2137/google-dark-theme#14]
Currently the theme seems to change the colours of charts in Google Sheets. As this style doesn't otherwise interfere with the contents of documents, just the Google UI itself I think this is probably a bug but if not making it optional might be a better idea.

![](https://i.imgur.com/xMIGA8q.gif)

Not sure if this affects other Google products but I'd imagine so.

Cheers in advance for any responses.

**Comment by blyad2137** [comment]
Sorry for not responding for a while, been too lazy playing FNV and meanwhile my pc blew up.
Just looking at this tells me that this is a bug(or not) correspondent to one of the newer feature.
You can just disable it and everything should be fine.

![obraz](https://user-images.githubusercontent.com/86572965/144482293-44862a97-3577-42d3-9fe2-54b658eb1bc1.png)
![obraz](https://user-images.githubusercontent.com/86572965/144482216-e9c3dcb0-0ef2-443b-911e-024c3b4a224e.png)
