### ISSUE TITLE
[GSheets] Illegible sheet names while renaming.

### ISSUE THREAD

**Issue by C4J3** [blyad2137/google-dark-theme#15]
![](https://i.imgur.com/feeIqBR.gif)

**Comment by blyad2137** [comment]
This should do the trick, of course this will be included in the next update.
`	.docs-gm .docs-sheet-tab-name[contenteditable="true"]:focus {
		border-color: var(--blue);
	}
	.docs-gm .docs-sheet-tab-name[contenteditable="true"] {
		color: var(--white-2);
	}`
	
![image](https://user-images.githubusercontent.com/86572965/144720888-23547e38-5741-4cfc-b650-3d5a6b66edfc.png)
