### ISSUE TITLE
[GDocs] Illegible text in special character menu.

### ISSUE THREAD

**Issue by C4J3** [blyad2137/google-dark-theme#16]
Me again,

![](https://i.imgur.com/wpYaJkH.gif)

P.S. Sorry for the constant complaints. Can't stand using GOffice or whatever it's called without this now but keep having slight problems. Cheers for all your work!

**Comment by C4J3** [comment]
Just noticed a similar problem with the Find and Replace menu in Google Sheets. I imagine it's the same thing.

**Comment by blyad2137** [comment]
Thanks for reporting, will look at this asap

**Comment by blyad2137** [comment]
Okay this should do this, just paste this somewhere in the code for now.
`	.docs-gm .modal-dialog .goog-flat-menu-button-caption, .docs-gm .kix-tablesidebar-control .goog-flat-menu-button-caption, .docs-gm .sketchy-shape-effects-shadow-tile .goog-flat-menu-button-caption {
		color: var(--white-3);
	}
	.docs-gm .modal-dialog .goog-flat-menu-button:active, .docs-gm .kix-tablesidebar-control .goog-flat-menu-button:active, .docs-gm .sketchy-shape-effects-shadow-tile .goog-flat-menu-button:active, .docs-findinput-container.docs-findinput-container {
		background-color: var(--bg-dark);
	}
	.ita-cp-lens, .modal-dialog-title-close:after {
		filter: var(--invert-1);
	}
	.ita-cp-search, .ita-cp-charpicker .goog-char-picker-grid {
		border-color: var(--grey-17);
	}
	.goog-char-picker-grid .goog-flat-button {
		border-bottom-color: var(--border-7);
		border-right-color: var(--border-7);
	}
	.goog-char-picker-grid .goog-flat-button-hover, .goog-char-picker-grid .goog-flat-button-focus {
		color: var(--bg-dark);
	}
	.ita-cp-hwt {
		background-color: var(--bg-dark);
		border-color: var(--grey-17);
	}
	.docs-gm .docs-menubar .goog-control-active, .docs-gm .docs-menubar .goog-control:hover:active {
		background-color: var(--bg-dark-blue-1);
	}
	.docs-gm .docs-findinput-container, .docs-gm .docs-gotoinput-container {
		border-color: var(--border-1);
		color: var(--white-4);
	}
	.docs-gm .modal-dialog button[disabled], .docs-gm .modal-dialog .jfk-button-standard.jfk-button-disabled {
		background-color: var(--bg-dark);
		border-color: var(--bg-dark-2) !important;
		color: var(--white-4);
	}
	.docs-findinput-count {
		color: var(--grey-1);
	}`
	
![image](https://user-images.githubusercontent.com/86572965/144751618-1b5b4b5e-1e0b-4606-b020-b482acd47c12.png)
