### ISSUE TITLE
Docs: Partially styled popup

### ISSUE THREAD

**Issue by ionnsachie** [blyad2137/google-dark-theme#18]
In Google docs I noticed there's a couple partially styled popups with rather unreadable text.  

First one is in the "See document status": 
![image](https://user-images.githubusercontent.com/95966225/145768753-bdcc02e2-dabf-4459-9f96-75da4bac7ca3.png)

Second one is a popup from "Review suggested edits", under the tools menu:  
![image](https://user-images.githubusercontent.com/95966225/145768905-feca81c4-c532-40ab-b8be-a019b50b6fd5.png)

**Comment by blyad2137** [comment]
? It just works, maybe you're using outdated version.
![image](https://user-images.githubusercontent.com/86572965/145868846-dd81032e-0d74-46ba-894a-1c53a7a898a7.png)

Should get the job done, `	.docs-slidingdialog {
		background-color: var(--bg-dark);
		border-bottom-color: var(--border-17);
		border-left-color: var(--border-17);
		border-right-color: var(--border-17);
	}`. Just paste this somewhere for now, update will come later this day or tomorrow, we will see.
![image](https://user-images.githubusercontent.com/86572965/145869157-44076154-e4a8-4eb9-9327-296ba1a2eccb.png)
