### ISSUE TITLE
[Feature Request] [GSheets] Whitespace colouring

### ISSUE THREAD

**Issue by C4J3** [blyad2137/google-dark-theme#19]
So in Google Sheets if your window is bigger than the actual sheet it just adds whitespace to the side. This is very unfun for my retina's :eyes: any chance you can darken it?

![](https://i.imgur.com/F1jwsVB.png)

**Comment by blyad2137** [comment]
I'm afraid that really I'm unable to do so, it's in the canvas which means there is no way for me to do so in standalone CSS.
You can apply some filters, but it will look how it will look + it will filter such things as photos, colors and possibly charts making them unreadable/not accurate to the original value.
![image](https://user-images.githubusercontent.com/86572965/147364088-7fb34614-de22-4554-8411-f854b505308a.png)

**Comment by C4J3** [comment]
Big sad. Thanks for checking!
