### ISSUE TITLE
There is something wrong with google drive recent tab

### ISSUE THREAD

**Issue by FatehMammadli** [blyad2137/google-dark-theme#2]
![image](https://user-images.githubusercontent.com/76201120/133242401-8c06cc60-f9b2-4b92-8db2-26e2e67fa8f1.png)

**Comment by blyad2137** [comment]
I see you'r using some old version its not that extreme in newest build, only borders and font color is unchanged, proper fix will drop in next update.
For now just update it to newer version, and paste this somewhere in the code:
`.aabwZd .Tguc8d {
	color: var(--white-54);
	border-color: var(--border-1);
}`

**Comment by FatehMammadli** [comment]
Can I find updated version in Stylus?
