### ISSUE TITLE
Google Drive broken?

### ISSUE THREAD

**Issue by C4J3** [blyad2137/google-dark-theme#20]
![image](https://user-images.githubusercontent.com/13005453/170718040-a90a765b-a1e5-4e27-b06d-cef9d413fa44.png)

Background is white as are un-highlighted items - selected items seems work. Some other items seem fine as well so I think a background layer is mis/renamed.

Let me know if I can give more info

**Comment by blyad2137** [comment]
They added an entire column of variables.
Just a matter of changing them to mine and correcting things a little bit.

**Comment by blyad2137** [comment]
Well, that should be about it

**Comment by C4J3** [comment]
Tested and working - cheers for the quick fix!
