### ISSUE TITLE
Google Sheets Formulas text colour

### ISSUE THREAD

**Issue by C4J3** [blyad2137/google-dark-theme#22]
Google sheets does weird formatting when editing formulas in cells to make them easier to read and it seems to be deciding what colour to use for the text based on the colour the text in the box it set to. This means when editing a 'dark mode' sheet (using Dark Grey 4 for cell background and Light Grey 2 for text) the formula text box becomes white/grey and the text stays grey making it illegible. 

![chrome_7PJFQYR0nd](https://user-images.githubusercontent.com/13005453/180608487-5f88af72-3bce-464c-bcf6-a65756f1604b.png)
![chrome_3UjbqF895o](https://user-images.githubusercontent.com/13005453/180608489-c9b4276a-cdee-4cfe-b8f9-94a42288c996.png)
![chrome_hI4p0z0acJ](https://user-images.githubusercontent.com/13005453/180608488-7b897bf3-b988-4dd1-8702-9683123740ff.png)

**Comment by blyad2137** [comment]
And done again.
![image](https://user-images.githubusercontent.com/86572965/180619624-a0849788-9b01-40b9-acc3-83ba9af7ec11.png)
Update to newest version and check if that was it

**Comment by C4J3** [comment]
Quick and phenomenal work as always - Tyvm!
