### ISSUE TITLE
Colour Picker Altering.

### ISSUE THREAD

**Issue by C4J3** [blyad2137/google-dark-theme#3]
This issue seems pretty standard in most darkening extensions I've seen but white is made black in the colour picker menu for fonts and cells in Google Sheets. This only seems to happen with 'full white' (#ffffff). Weirdly this issue doesn't seem to be present in Google Docs which I would assume uses the same system for it.

Edit: This also seems to work on text in formulas. This means typing '=<anything>' on white backgrounds causes all the text in the formula to turn white and become illegible. Kinda of a big problem in Sheets. ([link](https://www.dropbox.com/s/cevjvghydfdfzrs/t2eavXXzoL.mp4?dl=0))

**Docs:**
![Screenshot 2021-09-17 144439](https://user-images.githubusercontent.com/13005453/133793085-918ec6d7-0f05-4719-ac60-c2ec1646bbd7.png)
**Sheets Text:**
![Screenshot 2021-09-17 144538](https://user-images.githubusercontent.com/13005453/133793082-b122661e-ad33-4232-a850-76ab2841c283.png)
**Sheets Fill:**
![Screenshot 2021-09-17 144521](https://user-images.githubusercontent.com/13005453/133793084-37187c31-ec4e-405d-9f58-9ceeef25142f.png)

**Comment by blyad2137** [comment]
Will take a look at that

**Comment by blyad2137** [comment]
Ok figured it out, child element had class of " default-formula-text-color" which changed it to white while being editable(with '=').
Fix for this will drop in next update, for now paste this somewhere in the code:
`[class="cell-input editable"] bdo span {
	color: currentColor;
}
div#t-formula-bar-input {
	color: var(--white-1) !important;
}`

**Comment by C4J3** [comment]
Does this also fix the colour selector problem?

**Comment by blyad2137** [comment]
Okay I'm a total idiot, now i managed to fix it. Sorry for not responding I didn't get any notification and I had to check it manually.
`td#docs-material-colorpalette-cell-309 > [style="background-color: rgb(255, 255, 255);"], td#docs-material-colorpalette-cell-209 > [style="background-color: rgb(255, 255, 255);"], td#docs-material-colorpalette-cell-381 > [style], td#docs-material-colorpalette-cell-281 > [style] {
	background-color: var(--white-1) !important;
}`

**Comment by C4J3** [comment]
So it's fixed the issue for the fill tool on Sheets but text colour picker still has it. Might be because it's a different layer and could cause issues or it might be something on my end at this point. Happens on colours:
#ffffff
#fafafa
#f5f5f5

**Comment by blyad2137** [comment]
Okay I think I've managed to fix this everywhere, or a least in Sheets.

`.rnt3Ze[style="background-color: rgb(255, 255, 255);"], td[style="background-color: rgb(255, 255, 255);"], .docs-material-color-swatch-element.docs-material-color-swatch-color.docs-material-color-swatch-border[style="background-color: rgb(255, 255, 255);"] {
	background: #fff !important;
}
.rnt3Ze[style="background-color: rgb(245, 245, 245);"], td [style="background-color: rgb(245, 245, 245);"], .docs-material-color-swatch-element.docs-material-color-swatch-color.docs-material-color-swatch-border[style="background-color: rgb(245, 245, 245);"] {
	background-color: #f5f5f5 !important;
}
.rnt3Ze[style="background-color: rgb(250, 250, 250);"], td [style="background-color: rgb(250, 250, 250);"], .docs-material-color-swatch-element.docs-material-color-swatch-color.docs-material-color-swatch-border[style="background-color: rgb(250, 250, 250);"] {
	background-color: #fafafa !important;
}
.rnt3Ze[style="background-color: rgb(240, 246, 253);"], td [style="background-color: rgb(240, 246, 253);"], .docs-material-color-swatch-element.docs-material-color-swatch-color.docs-material-color-swatch-border[style="background-color: rgb(240, 246, 253);"] {
	background-color: #f0f6fd !important;
}
.rnt3Ze[style="background-color: rgb(26, 115, 232);"], td [style="background-color: rgb(26, 115, 232);"], .docs-material-color-swatch-element.docs-material-color-swatch-color.docs-material-color-swatch-border[style="background-color: rgb(26, 115, 232);"] {
	background-color: rgb(26, 115, 232) !important;
}`
