### ISSUE TITLE
Google Maps - New Sidebar Navigation

### ISSUE THREAD

**Issue by DJScias** [blyad2137/google-dark-theme#33]
Hello there,

Noticed the rollout started from a new [Google Maps sidebar navigation design](https://www.seroundtable.com/google-maps-new-sidebar-navigation-34438.html).

The styling is broken on the following:

- The new sidebar (obviously)
- The map dark invert also no longer functions.

I reckon that's not so much your fault as the fact it's not widely available yet.
But I figured I would at least post it here so it's known to be broken when it does release more widely.

Below is a screenshot that shows the sidebar on the left unstyled and maps not being inverted (despite it being enabled).
![image](https://user-images.githubusercontent.com/439655/207395587-51374437-ea9a-4606-bbf7-0d647de76a2d.png)

![image](https://user-images.githubusercontent.com/439655/207395161-03002d9c-91d4-41ae-8e1b-7dfffe016f88.png)

**Comment by blyad2137** [comment]
I've checked on 2 browsers, and it still does not appear for me.
Maps invert does not work because they've changed the class id with the new sidebar update so I can't fix that either.
I will fix this ASAP when I only get my hands on it.

**Comment by blyad2137** [comment]
possibly fixed, not sure tho.

**Comment by DJScias** [comment]
Can confirm it's fixed from my checking.
