### ISSUE TITLE
Google acoount iFrame - native dark theme

### ISSUE THREAD

**Issue by gitpro2005** [blyad2137/google-dark-theme#34]
The new redesigned account switcher iFrame (Material Design 3.0) has a native dark theme, you can see it in google.com with dark theme enabled.

However, in apps that don't have dark theme support by Google, the account switcher stays in light theme.

So, i inspected the iFrame and found the class that enables dark theme, then i went to the stylesheet and copied only the rules that contained that class (".aRDKUe"), and i removed the class from the rules, so the dark theme rules can be applied to the elements, enabling dark theme.

Here is the stylesheet i came up with, which applies all native dark theme rules to the account switcher:

[Google account iframe enable native dark theme.txt](https://github.com/blyad2137/google-dark-theme/files/10889765/Google.account.iframe.enable.native.dark.theme.txt)

You could add that to the code, and if you could not find the url match for the iFrame, you can just put "google.com" on domain match.

Thank you!

**Comment by blyad2137** [comment]
Just got the md 3.0 update, will fix this right away.
