### ISSUE TITLE
who the fuck is thalmor 

### ISSUE THREAD

**Issue by CoolingTool** [blyad2137/google-dark-theme#35]
![image](https://user-images.githubusercontent.com/62089272/223002982-7358b00a-6cde-47a8-8bcf-5f4c6909eb0c.png)
![image](https://user-images.githubusercontent.com/62089272/223002998-e183c420-f453-4c40-b60c-0479db2aa8b7.png)

**Comment by blyad2137** [comment]
Literal nazis in TES lore
https://elderscrolls.fandom.com/wiki/Thalmor_(Skyrim)
