### ISSUE TITLE
blurry misaligned text in google search bar

### ISSUE THREAD

**Issue by gmiwoj** [blyad2137/google-dark-theme#4]
![offset](https://user-images.githubusercontent.com/36712913/133944343-9a64769e-9afa-4ee0-9ee7-1e8294c7b1f0.PNG)
text in google search bar appears twice, misaligned by couple pixels **when red underline from spell checking error appears**

also btw i just noticed that red squiggly underline looks pretty bad on dark. just pointing out.

**Comment by blyad2137** [comment]
Replaced it with custom one, will drop in next update, for now paste this somewhere in the code:
`.pR49Ae span {
	background: none;
	border-bottom: 3px dotted #f00;
	top: -0.5em;
	position: relative;
	color: transparent;
}
.pR49Ae.gsfi {
	color: transparent;
}`

**Comment by MoneyAllDay** [comment]
I recently re-enabled this theme and this still occurs for me:

![screenshot 2022-10-29 06 53 57](https://user-images.githubusercontent.com/19583547/198816503-1b499670-a427-4233-badc-5720a8b21728.png)

Version 3.4.4

**Comment by blyad2137** [comment]
Fixed, will be pushed in next update.
If you want it right now just paste this somewhere in the code.
`.YacQv {
		visibility: hidden;
	}
	.YacQv span {
		visibility: hidden;
		position: relative;
	}
	.YacQv span::before {
		content: '';
		position: absolute;
		width: 100%;
		height: 100%;
		top: 1.1rem;
		left: 0;
		border-top: 3px dotted var(--red);
		visibility: visible;
	}`
