### ISSUE TITLE
Applies to iframes it probably shouldn't

### ISSUE THREAD

**Issue by IdrisQe** [blyad2137/google-dark-theme#40]
It seems that some login pages that have a "log in with Google" option get affected by the style, even when they probably shouldn't for consistency with the host website's style.

Reddit's login page for reference, normally it looks the same as the "Continue with Apple" option:
![image](https://user-images.githubusercontent.com/40530630/233815416-b74c9c87-68d4-4647-9cdc-b96012c4776b.png)

Edit: Enabling "Expose iframes via HTML[stylus-­iframe]" in Stylus settings seems to kind of fix it visually (though the Google "G" logo is still lightened)
![image](https://user-images.githubusercontent.com/40530630/233815806-4a4eb15c-76bd-45e4-80b1-4622b7253c39.png)

**Comment by blyad2137** [comment]
Expose iframe option fixes a lot of issues, thats why I put it above everything else in the description to avoid such cases. Fixed the lightened `G` too, will be released with next update.
