### ISSUE TITLE
Invisible or very faint fonts in Definitions and Translations parts at Google Translate

### ISSUE THREAD

**Issue by ediowar** [blyad2137/google-dark-theme#5]
![Screenshot_2021-09-20_11-55-09](https://user-images.githubusercontent.com/44164186/133998128-6e396331-22a4-45c0-9502-117d491d9c0e.png)

**Comment by blyad2137** [comment]
Its because of the background, give me a moment

**Comment by blyad2137** [comment]
Okay, everything is back to dark, paste this somewhere in the code. This will be included in the next update.
`.I87fLc.XzOhkf {
	background-color: var(--bg-dark);
	border-color: var(--border-1);
}
.nYkDR, .LV4pme, .VhOj3e {
	color: var(--grey-1);
}
.kgnlhe.FwR7Pc, .MtFg0.FwR7Pc {
	background-color: var(--bg-dark-2);
	color: var(--white-1);
}
.eIKIse, .jCVEDd .G2nOM, .mvqA2c, .ODAbH {
	color: var(--blue);
}
.ksE5nf.fXx9Lc {
	background-color: var(--border-1);
}
.ksE5nf.EiZ8Dd {
	background-color: var(--blue);
}
.L780X {
	background-color: var(--bg-dark);
	color: var(--grey-1);
}
.L780X::after {
	background-color: var(--bg-dark);
	box-shadow: -2px 2px 2px 0 rgba(82, 82, 82, .4) !important;
}`

**Comment by ediowar** [comment]
**blyad2137** Thanks It works.
