### ISSUE TITLE
Presentation has a small white tab

### ISSUE THREAD

**Issue by Unconventional10** [blyad2137/google-dark-theme#6]
There is an unchanged white tab that appears when closing the sidebar.
<img width="1057" alt="Screen Shot 2021-09-20 at 11 08 50 AM" src="https://user-images.githubusercontent.com/61166139/134068442-bba9c061-8979-4c2b-ad9d-77f79ffce924.png">

**Comment by blyad2137** [comment]
This should fix this, of course this will drop in next update, but you can paste it anywhere in the code.
`.companion-collapser-button.app-switcher-button-checked .app-switcher-button-icon-background, .companion-theme-light .companion-collapser-button.app-switcher-button-checked .app-switcher-button-icon-background {
	background-color: var(--bg-dark);
}
.companion-collapser-button.app-switcher-button-checked.app-switcher-button-hover .app-switcher-button-icon-background, .companion-theme-light .companion-collapser-button.app-switcher-button-checked.app-switcher-button-hover .app-switcher-button-icon-background {
	background-color: var(--bg-dark-2);
}`
