### ISSUE TITLE
There is something wrong with google photos

### ISSUE THREAD

**Issue by FatehMammadli** [blyad2137/google-dark-theme#7]
Hey sorry for bothering you that often. But I have this problem with google photo. And I wanted to ask where can I download the last version of this css.
![image](https://user-images.githubusercontent.com/76201120/135467368-603b4dfe-dd88-4262-9c17-e268f048f59d.png)

**Comment by blyad2137** [comment]
Latest version is always available here or at USw, doesn't matter.

**Comment by FatehMammadli** [comment]
The issue was about the white space. I fixed it no problem. But I was letting you know.

**Comment by blyad2137** [comment]
Thats good, just fixed it rn. This ofc will be included in the next update, thanks.
